Repository Planimal-Info/Flora-Fauna, pull requests merged in 2022-08, with the labels that each got.

#67 Update UI (landing page, user cards, navbar, search results)
  Flora-Fauna-Frontend/src/components/AnimalCards/AnimalCards.jsx
  Flora-Fauna-Frontend/src/components/LandingPage/LandingPage.css
  Flora-Fauna-Frontend/src/components/LandingPage/LandingPage.jsx
  Flora-Fauna-Frontend/src/components/ModalPopup/ModalPopup.css
  Flora-Fauna-Frontend/src/components/Navbar/Navbar.css
  Flora-Fauna-Frontend/src/components/SearchResults/SearchResults.css
  Flora-Fauna-Frontend/src/components/SearchResults/SearchResults.jsx
  Flora-Fauna-Frontend/src/components/UploadPage/UploadPage.css
  Flora-Fauna-Frontend/src/components/UploadPage/UploadPage.jsx
  Flora-Fauna-Frontend/src/components/UserCards/UserCards.css
  Flora-Fauna-Frontend/src/components/UserCards/UserCards.jsx
  Flora-Fauna-Frontend/src/components/UserFeed/UserFeed.css
  Flora-Fauna-Frontend/src/components/UserFeed/UserFeed.jsx
  Flora-Fauna-Frontend/src/index.css
Labels: enhancement

#75 updated report flags to actually report the post
  Flora-Fauna-Frontend/src/components/ModalPopup/ModalPopup.jsx
  Flora-Fauna-Frontend/src/components/UserCards/UserCards.jsx
Labels: bug

#77 add tooltip to notify users that post has been flagged
  Flora-Fauna-Frontend/src/components/UserCards/UserCards.css
  Flora-Fauna-Frontend/src/components/UserCards/UserCards.jsx
Labels: enhancement

#79 fixed issues with merge conflicts, also fixed bug with likes and adde…
  Flora-Fauna-Frontend/src/components/UserCards/UserCards.jsx
  Flora-Fauna-Frontend/src/contexts/posts.jsx
Labels: bug

#80 added routes, model fucntions and updated the components to show back…
  Flora-Fauna-Backend/models/planimal.js
  Flora-Fauna-Backend/routes/planimal.js
  Flora-Fauna-Frontend/src/components/AnimalCards/AnimalCards.jsx
  Flora-Fauna-Frontend/src/components/Hero/Hero.jsx
  Flora-Fauna-Frontend/src/components/SearchResults/SearchResults.jsx
  Flora-Fauna-Frontend/src/contexts/search.jsx
  Flora-Fauna-Frontend/src/services/ApiClient.js
Labels: enhancement

#81 fixed weird bug withs posts not showing when get more is clicked
  Flora-Fauna-Frontend/src/components/UserFeed/UserFeed.jsx
Labels: bug

#83 Connecting filters amaar
  Flora-Fauna-Backend/app.js
  Flora-Fauna-Backend/flora_and_fauna-schema.sql
  Flora-Fauna-Backend/models/filter.js
  Flora-Fauna-Backend/models/posts.js
  Flora-Fauna-Backend/routes/filter.js
  Flora-Fauna-Frontend/src/components/SearchFilter/SearchFilter.jsx
  Flora-Fauna-Frontend/src/components/UploadPage/UploadPage.jsx
  Flora-Fauna-Frontend/src/components/UserCards/UserCards.jsx
  Flora-Fauna-Frontend/src/components/UserFeed/UserFeed.css
  Flora-Fauna-Frontend/src/components/UserFeed/UserFeed.jsx
  Flora-Fauna-Frontend/src/contexts/posts.jsx
  Flora-Fauna-Frontend/src/services/ApiClient.js
Labels: enhancement

#87 added a admin details page for an admin to see the post if they wante…
  Flora-Fauna-Backend/routes/posts.js
  Flora-Fauna-Frontend/src/components/AdminDetails/AdminDetails.css
  Flora-Fauna-Frontend/src/components/AdminDetails/AdminDetails.jsx
  Flora-Fauna-Frontend/src/components/AdminOverview/AdminOverview.jsx
  Flora-Fauna-Frontend/src/components/App/App.jsx
  Flora-Fauna-Frontend/src/contexts/admin.jsx
  Flora-Fauna-Frontend/src/services/ApiClient.js
Labels: enhancement

#88 Animal details fix
  Flora-Fauna-Frontend/src/components/Hero/Hero.css
  Flora-Fauna-Frontend/src/components/Hero/Hero.jsx
  Flora-Fauna-Frontend/src/index.css
Labels: small fix

#89 Post bugfix amaar
  Flora-Fauna-Backend/models/posts.js
  Flora-Fauna-Backend/routes/posts.js
  Flora-Fauna-Backend/utils/tokens.js
  Flora-Fauna-Frontend/src/components/AdminDetails/AdminDetails.css
  Flora-Fauna-Frontend/src/components/AdminDetails/AdminDetails.jsx
  Flora-Fauna-Frontend/src/components/AdminOverview/AdminOverview.jsx
  Flora-Fauna-Frontend/src/components/SearchResults/SearchResults.jsx
  Flora-Fauna-Frontend/src/contexts/admin.jsx
  Flora-Fauna-Frontend/src/contexts/posts.jsx
  Flora-Fauna-Frontend/src/services/ApiClient.js
Labels: enhancement

#91 Unflag post amaar
  Flora-Fauna-Backend/models/admin.js
  Flora-Fauna-Backend/routes/admin.js
  Flora-Fauna-Frontend/src/components/AdminDetails/AdminDetails.css
  Flora-Fauna-Frontend/src/components/AdminDetails/AdminDetails.jsx
  Flora-Fauna-Frontend/src/components/AdminOverview/AdminOverview.jsx
  Flora-Fauna-Frontend/src/components/UserCards/UserCards.jsx
  Flora-Fauna-Frontend/src/contexts/admin.jsx
  Flora-Fauna-Frontend/src/services/ApiClient.js
Labels: enhancement

#92 User profiles
  Flora-Fauna-Backend/app.js
  Flora-Fauna-Backend/flora_and_fauna-schema.sql
  Flora-Fauna-Backend/middleware/security.js
  Flora-Fauna-Backend/models/profile.js
  Flora-Fauna-Backend/profile.js
  Flora-Fauna-Backend/routes/profile.js
  Flora-Fauna-Frontend/package.json
Labels: enhancement

#93 comment out image url input
  Flora-Fauna-Frontend/src/components/UploadPage/UploadPage.css
  Flora-Fauna-Frontend/src/components/UploadPage/UploadPage.jsx
Labels: small fix

#95 Fix likes amaar
  Flora-Fauna-Frontend/src/components/Navbar/Navbar.jsx
  Flora-Fauna-Frontend/src/components/UserCards/UserCards.jsx
  Flora-Fauna-Frontend/src/components/UserFeed/UserFeed.jsx
Labels: bug

#96 add resources page and link back to navbar
  Flora-Fauna-Frontend/src/components/App/App.jsx
  Flora-Fauna-Frontend/src/components/Navbar/Navbar.jsx
  Flora-Fauna-Frontend/src/components/ResourcesPage/ResourcesPage.css
  Flora-Fauna-Frontend/src/components/ResourcesPage/ResourcesPage.jsx
Labels: small fix

#97 made it so that the Sort categories of filters work on its own. Added…
  Flora-Fauna-Backend/models/posts.js
  Flora-Fauna-Backend/routes/posts.js
  Flora-Fauna-Frontend/src/components/SearchFilter/SearchFilter.jsx
  Flora-Fauna-Frontend/src/contexts/posts.jsx
  Flora-Fauna-Frontend/src/services/ApiClient.js
Labels: enhancement

#101 Landing page fix
  Flora-Fauna-Frontend/index.html
  Flora-Fauna-Frontend/src/components/AboutPage/AboutPage.css
  Flora-Fauna-Frontend/src/components/AboutPage/AboutPage.jsx
  Flora-Fauna-Frontend/src/components/App/App.jsx
  Flora-Fauna-Frontend/src/components/Footer/Footer.css
  Flora-Fauna-Frontend/src/components/Footer/Footer.jsx
  Flora-Fauna-Frontend/src/components/LandingPage/LandingPage.css
  Flora-Fauna-Frontend/src/components/LandingPage/LandingPage.jsx
  Flora-Fauna-Frontend/src/components/Navbar/Navbar.css
  Flora-Fauna-Frontend/src/components/Navbar/Navbar.jsx
  Flora-Fauna-Frontend/src/index.css
Labels: small fix

#102 Footer position fix
  Flora-Fauna-Backend/package-lock.json
  Flora-Fauna-Frontend/src/components/App/App.jsx
  Flora-Fauna-Frontend/src/components/Footer/Footer.css
  Flora-Fauna-Frontend/src/components/Footer/Footer.jsx
  Flora-Fauna-Frontend/src/components/LandingPage/LandingPage.jsx
  Flora-Fauna-Frontend/src/components/LoginPage/LoginPage.css
  Flora-Fauna-Frontend/src/components/LoginPage/LoginPage.jsx
  Flora-Fauna-Frontend/src/components/RegistrationPage/RegistrationPage.css
  Flora-Fauna-Frontend/src/components/RegistrationPage/RegistrationPage.jsx
  Flora-Fauna-Frontend/src/components/ResourcesPage/ResourcesPage.css
  Flora-Fauna-Frontend/src/components/ResourcesPage/ResourcesPage.jsx
  Flora-Fauna-Frontend/src/components/SearchResults/SearchResults.css
  Flora-Fauna-Frontend/src/components/SearchResults/SearchResults.jsx
  Flora-Fauna-Frontend/src/components/UploadPage/UploadPage.css
  Flora-Fauna-Frontend/src/components/UploadPage/UploadPage.jsx
  Flora-Fauna-Frontend/src/components/UserFeed/UserFeed.css
  Flora-Fauna-Frontend/src/components/UserFeed/UserFeed.jsx
  Flora-Fauna-Frontend/src/components/UserProfile/UserProfile.css
  Flora-Fauna-Frontend/src/components/UserProfile/UserProfile.jsx
  Flora-Fauna-Frontend/src/index.css
Labels: bug

#104 Media queries
  Flora-Fauna-Frontend/src/components/AboutPage/AboutPage.css
  Flora-Fauna-Frontend/src/components/LandingPage/LandingPage.css
  Flora-Fauna-Frontend/src/components/LoginPage/LoginPage.css
  Flora-Fauna-Frontend/src/components/Logo/Logo.css
  Flora-Fauna-Frontend/src/components/Logo/Logo.jsx
  Flora-Fauna-Frontend/src/components/Navbar/Navbar.css
  Flora-Fauna-Frontend/src/components/Navbar/Navbar.jsx
  Flora-Fauna-Frontend/src/components/RegistrationPage/RegistrationPage.css
Labels: enhancement

#105 implemented users being able to unlike a post they previously liked, …
  Flora-Fauna-Backend/flora_and_fauna-schema.sql
  Flora-Fauna-Backend/models/posts.js
  Flora-Fauna-Backend/routes/posts.js
  Flora-Fauna-Frontend/src/components/UserCards/UserCards.jsx
  Flora-Fauna-Frontend/src/components/UserFeed/UserFeed.jsx
  Flora-Fauna-Frontend/src/contexts/posts.jsx
  Flora-Fauna-Frontend/src/services/ApiClient.js
Labels: bug

#110 added users being able to see there liked posts
  Flora-Fauna-Backend/models/user.js
  Flora-Fauna-Backend/routes/auth.js
  Flora-Fauna-Frontend/src/components/UserCards/UserCards.jsx
  Flora-Fauna-Frontend/src/components/UserProfile/UserProfile.jsx
  Flora-Fauna-Frontend/src/contexts/auth.jsx
  Flora-Fauna-Frontend/src/services/ApiClient.js
Labels: enhancement

#111 Small fixes
  Flora-Fauna-Frontend/src/components/AccessForbidden/AccessForbidden.css
  Flora-Fauna-Frontend/src/components/Hero/Hero.css
  Flora-Fauna-Frontend/src/components/LoginPage/LoginPage.css
  Flora-Fauna-Frontend/src/components/Navbar/Navbar.css
  Flora-Fauna-Frontend/src/components/NotFound/NotFound.css
  Flora-Fauna-Frontend/src/components/RegistrationPage/RegistrationPage.css
  Flora-Fauna-Frontend/src/components/RegistrationPage/RegistrationPage.jsx
  Flora-Fauna-Frontend/src/components/UploadPage/UploadPage.css
  Flora-Fauna-Frontend/src/components/UserCards/UserCards.css
Labels: small fix

#115 User profile styles
  Flora-Fauna-Frontend/src/components/AnimalCards/AnimalCards.css
  Flora-Fauna-Frontend/src/components/LandingPage/LandingPage.jsx
  Flora-Fauna-Frontend/src/components/UserCards/UserCards.css
  Flora-Fauna-Frontend/src/components/UserProfile/UserProfile.css
  Flora-Fauna-Frontend/src/components/UserProfile/UserProfile.jsx
Labels: enhancement
